version: '3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    command: "npm ${NPMCOMMAND}"
    volumes:
      - "${LOCATION}:/usr/app/"
      - /usr/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET=${SECRET}
      - JWT_KEY=${JWT_KEY}

  postgres:
    build: ./db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports: 
      - "5432:5432"
