version: '3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    command: "npm ${NPMCOMMAND}"
    volumes:
      - "${LOCATION}:/app/"
      - /app/node_modules
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET=${SECRET}
      - JWT_KEY=${JWT_KEY}

  postgres:
    restart: always
    image: postgres:10.4
    ports:
      - "5432:5432" 
    volumes: 
      - ./sql/create_tables.sql:/docker-entrypoint-initrb.d/init.sql
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      # - POSTGRES_DB=database

volumes: 
  sql:

