version: '3'

services:
  # db: 
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_PASSWORD=example
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: "npm ${NPMCOMMAND}"
    volumes:
      - "${LOCATION}:/app/"
      - /app/node_modules
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET=${SECRET}
      - JWT_KEY=${JWT_KEY}


